name: Bug Reports Only (Feature requests and questions should be raised in the 'Discussions' tab above)
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
 - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Carefully read and work through this check list in order to prevent misuse of issues
      options:
        - label: I am reporting a bug in the Onion OS
          required: true
        - label: I have reviewed the Onion Wiki and did not find the answer ([Wiki](https://github.com/Sichroteph/Onion/wiki))
          required: true
        - label: I have searched the existing (open and closed) issues to ensure I do not log a duplicate
          required: true

